# Generated by Django 4.2 on 2024-05-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0002_security_created_at_security_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='updated_price_at',
            field=models.DateTimeField(null=True),
        ),
    ]
