# Generated by Django 4.2 on 2024-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0003_alter_security_updated_price_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='ticker',
            field=models.TextField(unique=True),
        ),
    ]
