# Generated by Django 4.2 on 2024-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0004_alter_security_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='id',
        ),
        migrations.RemoveField(
            model_name='security',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='security',
            name='updated_price_at',
        ),
        migrations.AlterField(
            model_name='security',
            name='ticker',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
