# Generated by Django 4.2 on 2024-05-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0005_remove_security_id_remove_security_last_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlistitem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='ticker',
            field=models.TextField(db_index=True),
        ),
    ]
