# Generated by Django 4.2 on 2024-05-27 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casestudy', '0007_remove_watchlistitem_ticker_watchlistitem_security'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'security')},
        ),
    ]
